apiVersion: apps/v1
kind: Pod
metadata:
  name: test-01-app
  labels:
    name: test-01-app
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"