apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-01-ingress
  labels:
    name: test-01-ingress
spec:
  defaultBackend:
    service:
      name: test-app
      port:
        number: 10080
