apiVersion: apps/v1
kind: Service
metadata:
  name: test-01-svc
  anotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  type: NodePort
  selector:
    app: test-01-app
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 10080
    targetPort: 80
